AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  Exclude:
    - "**/*_spec.rb"

# This cop is annoying. We might want to make this work on an old Ruby sometime,
# so STFU.
Style/SafeNavigation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
