AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - "**/*_spec.rb"

# This cop is annoying. We might want to make this work on an old Ruby sometime,
# so STFU.
Style/SafeNavigation:
  Enabled: false

# Don't care about frozen string literals because we don't have any string literals.
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
